---
version: 1
disable_existing_loggers: False
formatters:
    simple:
        format: "%(asctimes)s - %(name)s - %(levelname)s - %(message)s"

handlers:
    console:
        calss: logging.StreamHandler
        level: DEBUG
        formatter: simple
        stream: ext://sys.stdout
    
    info_file_handler:
        class: logging.handlers.RotatingFileHandler
        level: INFO
        formatter: simple
        filename: wsamba.info
        maxBytes: 10485760
        backupCount: 20
        encoding: utf-8

    error_file_handler:
        class: logging.handlers.RotatingFileHandler
        level: ERROR
        formatter: simple
        filename: wsamba.error
        maxBytes: 10485760
        backupCount: 20
        encoding: utf-8
    
loggers:
    my_moduel:
        level: ERROR
        handlers: [console]
        propagate: no

root:
    level: INFO
    handlers: [console,info_file_handler,errro_file_handler]
